require_relative '../node_modules/react-native/scripts/react_native_pods'

# React Native 0.76 requires iOS 14.0 minimum
platform :ios, '15.1'
install! 'cocoapods', :deterministic_uuids => false

target 'AmazonIvsExample' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'amazon-ivs-react-native-player', :path => '../..'

  post_install do |installer|
    react_native_post_install(installer)
  end
end
